STATES = [
    'alba',
    'arad',
    'arges',
    'bacau',
    'bihor',
    'bistrita-nasaud',
    'botosani',
    'braila',
    'brasov',
    'bucharest',
    'buzau',
    'calarasi',
    'caras-severin',
    'cluj',
    'constanta',
    'covasna',
    'dambovita',
    'dolj',
    'galati',
    'giurgiu',
    'gorj',
    'harghita',
    'hunedoara',
    'ialomita',
    'iasi',
    'ilfov',
    'maramures',
    'mehedinti',
    'mures',
    'neamt',
    'olt',
    'prahova',
    'salaj',
    'satu mare',
    'sibiu',
    'suceava',
    'teleorman',
    'timis',
    'tulcea',
    'valcea',
    'vaslui',
    'vrancea',
]

CITIES = [
    'adjud',
    'aiud',
    'alba iulia',
    'alexandria',
    'arad',
    'bacau',
    'baia mare',
    'bailesti',
    'barlad',
    'bistrita',
    'bolintin-vale',
    'botosani',
    'braila',
    'brasov',
    'buftea',
    'busteni',
    'buzau',
    'calafat',
    'calarasi',
    'campia turzii',
    'campina',
    'campulung',
    'caracal',
    'caransebes',
    'carei',
    'cernavoda',
    'cisnadie',
    'cluj-napoca',
    'codlea',
    'comanesti',
    'constanta',
    'craiova',
    'curtea de arges',
    'dej',
    'deva',
    'dorohoi',
    'dragasani',
    'drobeta-turnu severin',
    'eforie',
    'fagaras',
    'falticeni',
    'fetesti',
    'floresti',
    'focsani',
    'galati',
    'gheorgheni',
    'gherla',
    'giurgiu',
    'huedin',
    'hunedoara',
    'husi',
    'ianca',
    'iasi',
    'ineu',
    'jimbolia',
    'lipova',
    'lugoj',
    'lupeni',
    'macin',
    'mangalia',
    'marghita',
    'medgidia',
    'medias',
    'miercurea ciuc',
    'mioveni',
    'moinesti',
    'moreni',
    'motru',
    'nasaud',
    'navodari',
    'odorheiu secuiesc',
    'oltenita',
    'onesti',
    'oradea',
    'pantelimon',
    'pascani',
    'petrosani',
    'piatra neamt',
    'pitesti',
    'ploiesti',
    'pucioasa',
    'radauti',
    'ramnicu sarat',
    'ramnicu valcea',
    'rasnov',
    'recas',
    'reghin',
    'resita',
    'roman',
    'rosiorii de vede',
    'sacele',
    'salonta',
    'sangeorz-bai',
    'sannicolau mare',
    'satu mare',
    'sebes',
    'sector 1',
    'sector 2',
    'sector 3',
    'sector 4',
    'sector 5',
    'sector 6',
    'sfantu gheorghe',
    'sibiu',
    'sighetu marmatiei',
    'sighisoara',
    'simleu silvaniei',
    'sinaia',
    'slatina',
    'slobozia',
    'strehaia',
    'suceava',
    'targoviste',
    'targu frumos',
    'targu jiu',
    'targu mures',
    'targu neamt',
    'targu secuiesc',
    'tecuci',
    'timisoara',
    'topoloveni',
    'tulcea',
    'turda',
    'vaslui',
    'voluntari',
    'zalau',
    'zarnesti',
]

TYPE_MAP = {
    'street': 'strada',
    'st': 'strada',
    'avenue': 'bulevardul',
    'square': 'piata',
    'alley': 'aleea',
    'road': 'calea',
    'bd': 'bulevardul',
    'boulevard': 'bulevardul',
}
