PATTERNS = [
    {'label': 'TRANSPORT', 'pattern': 'walking'},
    {'label': 'TRANSPORT', 'pattern': 'walk'},
    {'label': 'TRANSPORT', 'pattern': 'by foot'},
    {'label': 'TRANSPORT', 'pattern': 'foot'},
    {'label': 'TRANSPORT', 'pattern': 'on foot'},
    {'label': 'TRANSPORT', 'pattern': 'pedestrian'},
    {'label': 'TRANSPORT', 'pattern': 'ped'},
    {'label': 'TRANSPORT', 'pattern': 'walking fast'},
    {'label': 'TRANSPORT', 'pattern': 'walk fast'},
    {'label': 'TRANSPORT', 'pattern': 'strolling'},
    {'label': 'TRANSPORT', 'pattern': 'stroll'},
    {'label': 'TRANSPORT', 'pattern': 'legwork'},
    {'label': 'TRANSPORT', 'pattern': 'hiking'},
    {'label': 'TRANSPORT', 'pattern': 'trekking'},
    {'label': 'TRANSPORT', 'pattern': 'marching'},
    {'label': 'TRANSPORT', 'pattern': 'ambulating'},
    {'label': 'TRANSPORT', 'pattern': 'rambling'},
    {'label': 'TRANSPORT', 'pattern': 'wander'},
    {'label': 'TRANSPORT', 'pattern': 'wandering'},
    {'label': 'TRANSPORT', 'pattern': 'traveling on foot'},
    {'label': 'TRANSPORT', 'pattern': 'hoofing it'},
    {'label': 'TRANSPORT', 'pattern': 'hoof'},
    {'label': 'TRANSPORT', 'pattern': 'by walking'},
    {'label': 'TRANSPORT', 'pattern': 'walks'},
    {'label': 'TRANSPORT', 'pattern': 'walked'},
    {'label': 'TRANSPORT', 'pattern': 'go by foot'},
    {'label': 'TRANSPORT', 'pattern': 'go on foot'},
    {'label': 'TRANSPORT', 'pattern': 'move on foot'},
    {'label': 'TRANSPORT', 'pattern': 'take a walk'},
    {'label': 'TRANSPORT', 'pattern': 'do a walk'},
    {'label': 'TRANSPORT', 'pattern': 'foot travel'},
    {'label': 'TRANSPORT', 'pattern': 'foot trip'},
    {'label': 'TRANSPORT', 'pattern': 'walk trip'},
    {'label': 'TRANSPORT', 'pattern': 'perambulate'},
    {'label': 'TRANSPORT', 'pattern': 'perambulating'},
    {'label': 'TRANSPORT', 'pattern': 'walk commute'},
    {'label': 'TRANSPORT', 'pattern': 'walk around'},
    {'label': 'TRANSPORT', 'pattern': 'local walk'},
    {'label': 'TRANSPORT', 'pattern': 'foot commute'},
    {'label': 'TRANSPORT', 'pattern': 'ambulate'},
    {'label': 'TRANSPORT', 'pattern': 'leg travel'},
    {'label': 'TRANSPORT', 'pattern': 'ramble'},
    {'label': 'TRANSPORT', 'pattern': 'hike'},
    {'label': 'TRANSPORT', 'pattern': 'footpath'},
    {'label': 'TRANSPORT', 'pattern': 'foot route'},
    {'label': 'TRANSPORT', 'pattern': 'walk route'},
    {'label': 'TRANSPORT', 'pattern': 'ped route'},
    {'label': 'TRANSPORT', 'pattern': 'walk mode'},
    {'label': 'TRANSPORT', 'pattern': 'walk method'},
    {'label': 'TRANSPORT', 'pattern': 'walking method'},
    {'label': 'TRANSPORT', 'pattern': 'on my feet'},
    {'label': 'TRANSPORT', 'pattern': 'driving'},
    {'label': 'TRANSPORT', 'pattern': 'drive'},
    {'label': 'TRANSPORT', 'pattern': 'by car'},
    {'label': 'TRANSPORT', 'pattern': 'car'},
    {'label': 'TRANSPORT', 'pattern': 'using car'},
    {'label': 'TRANSPORT', 'pattern': 'using a car'},
    {'label': 'TRANSPORT', 'pattern': 'auto'},
    {'label': 'TRANSPORT', 'pattern': 'automobile'},
    {'label': 'TRANSPORT', 'pattern': 'by automobile'},
    {'label': 'TRANSPORT', 'pattern': 'vehicle'},
    {'label': 'TRANSPORT', 'pattern': 'motor vehicle'},
    {'label': 'TRANSPORT', 'pattern': 'motorcar'},
    {'label': 'TRANSPORT', 'pattern': 'motor car'},
    {'label': 'TRANSPORT', 'pattern': 'by road'},
    {'label': 'TRANSPORT', 'pattern': 'road trip'},
    {'label': 'TRANSPORT', 'pattern': 'by driving'},
    {'label': 'TRANSPORT', 'pattern': 'car ride'},
    {'label': 'TRANSPORT', 'pattern': 'in car'},
    {'label': 'TRANSPORT', 'pattern': 'with car'},
    {'label': 'TRANSPORT', 'pattern': 'by auto'},
    {'label': 'TRANSPORT', 'pattern': 'by machine'},
    {'label': 'TRANSPORT', 'pattern': 'four wheeler'},
    {'label': 'TRANSPORT', 'pattern': 'drives'},
    {'label': 'TRANSPORT', 'pattern': 'drove'},
    {'label': 'TRANSPORT', 'pattern': 'car travel'},
    {'label': 'TRANSPORT', 'pattern': 'car commuting'},
    {'label': 'TRANSPORT', 'pattern': 'self driving'},
    {'label': 'TRANSPORT', 'pattern': 'driven'},
    {'label': 'TRANSPORT', 'pattern': 'go by car'},
    {'label': 'TRANSPORT', 'pattern': 'travel by car'},
    {'label': 'TRANSPORT', 'pattern': 'vehicle trip'},
    {'label': 'TRANSPORT', 'pattern': 'engine vehicle'},
    {'label': 'TRANSPORT', 'pattern': 'using automobile'},
    {'label': 'TRANSPORT', 'pattern': 'road'},
    {'label': 'TRANSPORT', 'pattern': 'highway travel'},
    {'label': 'TRANSPORT', 'pattern': 'road driving'},
    {'label': 'TRANSPORT', 'pattern': 'motor'},
    {'label': 'TRANSPORT', 'pattern': 'motoring'},
    {'label': 'TRANSPORT', 'pattern': 'traveling by car'},
    {'label': 'TRANSPORT', 'pattern': 'machine ride'},
    {'label': 'TRANSPORT', 'pattern': 'auto mode'},
    {'label': 'TRANSPORT', 'pattern': 'auto route'},
    {'label': 'TRANSPORT', 'pattern': 'driving mode'},
    {'label': 'TRANSPORT', 'pattern': 'driving commute'},
    {'label': 'TRANSPORT', 'pattern': 'drive route'},
    {'label': 'TRANSPORT', 'pattern': 'personal vehicle'},
    {'label': 'TRANSPORT', 'pattern': 'in my car'},
    {'label': 'TRANSPORT', 'pattern': 'on four wheels'},
    {'label': 'TRANSPORT', 'pattern': 'transit'},
    {'label': 'TRANSPORT', 'pattern': 'bus'},
    {'label': 'TRANSPORT', 'pattern': 'by bus'},
    {'label': 'TRANSPORT', 'pattern': 'train'},
    {'label': 'TRANSPORT', 'pattern': 'metro'},
    {'label': 'TRANSPORT', 'pattern': 'subway'},
    {'label': 'TRANSPORT', 'pattern': 'tram'},
    {'label': 'TRANSPORT', 'pattern': 'trolley'},
    {'label': 'TRANSPORT', 'pattern': 'public transport'},
    {'label': 'TRANSPORT', 'pattern': 'public transit'},
    {'label': 'TRANSPORT', 'pattern': 'mass transit'},
    {'label': 'TRANSPORT', 'pattern': 'rail'},
    {'label': 'TRANSPORT', 'pattern': 'light rail'},
    {'label': 'TRANSPORT', 'pattern': 'heavy rail'},
    {'label': 'TRANSPORT', 'pattern': 'shuttle'},
    {'label': 'TRANSPORT', 'pattern': 'coach'},
    {'label': 'TRANSPORT', 'pattern': 'commuter train'},
    {'label': 'TRANSPORT', 'pattern': 'commuter rail'},
    {'label': 'TRANSPORT', 'pattern': 'express bus'},
    {'label': 'TRANSPORT', 'pattern': 'city bus'},
    {'label': 'TRANSPORT', 'pattern': 'local bus'},
    {'label': 'TRANSPORT', 'pattern': 'trans'},
    {'label': 'TRANSPORT', 'pattern': 'pt'},
    {'label': 'TRANSPORT', 'pattern': 'via transit'},
    {'label': 'TRANSPORT', 'pattern': 'via bus'},
    {'label': 'TRANSPORT', 'pattern': 'via train'},
    {'label': 'TRANSPORT', 'pattern': 'via metro'},
    {'label': 'TRANSPORT', 'pattern': 'by metro'},
    {'label': 'TRANSPORT', 'pattern': 'tramway'},
    {'label': 'TRANSPORT', 'pattern': 'streetcar'},
    {'label': 'TRANSPORT', 'pattern': 'cable car'},
    {'label': 'TRANSPORT', 'pattern': 'monorail'},
    {'label': 'TRANSPORT', 'pattern': 'transit ride'},
    {'label': 'TRANSPORT', 'pattern': 'public commute'},
    {'label': 'TRANSPORT', 'pattern': 'transit commute'},
    {'label': 'TRANSPORT', 'pattern': 'bus route'},
    {'label': 'TRANSPORT', 'pattern': 'train route'},
    {'label': 'TRANSPORT', 'pattern': 'metro route'},
    {'label': 'TRANSPORT', 'pattern': 'subway ride'},
    {'label': 'TRANSPORT', 'pattern': 'train ride'},
    {'label': 'TRANSPORT', 'pattern': 'bus travel'},
    {'label': 'TRANSPORT', 'pattern': 'metro travel'},
    {'label': 'TRANSPORT', 'pattern': 'public route'},
    {'label': 'TRANSPORT', 'pattern': 'city transit'},
    {'label': 'TRANSPORT', 'pattern': 'urban transit'},
    {'label': 'TRANSPORT', 'pattern': 'trans method'},
    {'label': 'TRANSPORT', 'pattern': 'mass transit ride'},
    {'label': 'TRANSPORT', 'pattern': 'light rail travel'},
]
